---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: airflow
  labels:
    app: localstack
spec:
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack
          ports:
            - containerPort: 4566
              name: s3
          env:
            - name: SERVICES
              value: s3
            - name: HOSTNAME_EXTERNAL
              value: localstack.local
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
            - name: localstack-init
              mountPath: /docker-entrypoint-initaws.d
              readOnly: true
      volumes:
        - name: localstack-init
          configMap:
            name: localstack-init
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-init
  namespace: airflow
data:
  init_s3.sh: |
    awslocal s3 mb s3://airflow
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: airflow
  labels:
    app: localstack
spec:
  selector:
    app: localstack
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: s3
      port: 4566
      targetPort: s3
