---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow
  namespace: airflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow
  namespace: airflow
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - watch
      - create
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow
  namespace: airflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow
subjects:
  - kind: ServiceAccount
    name: airflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: airflow
  name: airflow-scheduler
  namespace: airflow
spec:
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      serviceAccountName: airflow
      containers:
        - name: scheduler
          image: registry.local:5000/scheduler
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql://airflow:password@airflow-postgresql:5432/airflow
            - name: AIRFLOW__CORE__EXECUTOR
              value: KubernetesExecutor
            # - name: AIRFLOW__KUBERNETES__GIT_REPO
            #   value: https://github.com/jtnz/airflow-in-k8s-experiment.git
            # - name: AIRFLOW__KUBERNETES__GIT_SUBPATH
            #   value: dags
            # - name: AIRFLOW__KUBERNETES__GIT_BRANCH
            #   value: master
            # - name: AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT
            #   value: "{AIRFLOW_HOME}/dags"
            # - name: AIRFLOW__KUBERNETES__DAGS_IN_IMAGE
            #   value: "true"
            # - name: AIRFLOW__CORE__DAGS_FOLDER
            #   value: /dags
            - name: AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY
              value: registry.local:5000/base_image
            - name: AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG
              value: latest
            - name: AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE_PULL_POLICY
              value: Always
            - name: AIRFLOW__KUBERNETES__NAMESPACE
              value: airflow
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
