---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: airflow
  labels:
    app: airflow
spec:
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
        - name: webserver
          image: registry.local:5000/webserver
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql://airflow:password@airflow-postgresql:5432/airflow
            - name: AIRFLOW__CORE__EXECUTOR
              value: KubernetesExecutor
            - name: AIRFLOW__CORE__FERNET_KEY
              value: PUlSbKcKvEHVJew0x6tLlHOIjjTTlpzU8KRJE5vItXM=
            - name: AIRFLOW__KUBERNETES__GIT_REPO
              value: https://github.com/jtnz/airflow-in-k8s-experiment.git
            - name: AIRFLOW__KUBERNETES__GIT_BRANCH
              value: master
            - name: AIRFLOW__KUBERNETES__GIT_SUBPATH
              value: dags
            - name: AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT
              value: /dags
            - name: AIRFLOW__CORE__DAGS_FOLDER
              value: /dags/repo/dags
            - name: AIRFLOW__CORE__REMOTE_LOGGING
              value: 'True'
            - name: AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER
              value: s3://airflow/logs
            - name: AIRFLOW__CORE__REMOTE_LOG_CONN_ID
              value: localstack_s3
          readinessProbe:
            httpGet:
              path: /admin/
              port: http
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
          - mountPath: /dags
            name: git
        - name: git-sync
          image: k8s.gcr.io/git-sync:v3.1.6
          env:
            - name: GIT_SYNC_REPO
              value: https://github.com/jtnz/airflow-in-k8s-experiment.git
            - name: GIT_SYNC_BRANCH
              value: master
            - name: GIT_SYNC_DEST
              value: repo
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
          - mountPath: /tmp/git
            name: git
      volumes:
      - name: git
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: airflow
  labels:
    app: airflow-webserver
spec:
  selector:
    app: airflow-webserver
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: airflow-webserver
  namespace: airflow
  labels:
    app: airflow
spec:
  rules:
    - host: airflow.local
      http:
        paths:
          - path: /
            backend:
              serviceName: airflow-webserver
              servicePort: http
